In [1]:
import pandas as pd

In [2]:
customers = pd.read_csv(r"D:\Customer Sales & Business Performance Analytics\customer_sales_analytics_dataset\customers.csv")
products = pd.read_csv(r"D:\Customer Sales & Business Performance Analytics\customer_sales_analytics_dataset\products.csv")
orders = pd.read_csv(r"D:\Customer Sales & Business Performance Analytics\customer_sales_analytics_dataset\orders.csv")
order_items = pd.read_csv(r"D:\Customer Sales & Business Performance Analytics\customer_sales_analytics_dataset\order_items.csv")

In [3]:
print("Customers:", customers.shape)
print("Products:", products.shape)
print("Orders:", orders.shape)
print("Order Items:", order_items.shape)

Customers: (5010, 9)
Products: (200, 6)
Orders: (20000, 6)
Order Items: (40000, 5)

In [4]:
display(customers.head())
display(products.head())
display(orders.head())
display(order_items.head())

,Customer_ID,Customer_Name,Gender,Age,City,State,Region,Customer_Segment,Registration_Date
0,CUST00001,Isha Mishra,Male,38,Ahmedabad,Gujarat,West,Consumer,2025-05-23
1,CUST00002,Amit Rao,Male,47,Lucknow,Uttar Pradesh,North,Consumer,2022-05-11
2,CUST00003,Rahul Rao,Female,28,Pune,Maharashtra,West,Consumer,2023-04-05
3,CUST00004,Divya Naidu,Male,28,Jaipur,Rajasthan,North,Corporate,2023-12-01
4,CUST00005,Varun Joshi,Male,19,Ranchi,Jharkhand,East,Small Business,2025-02-28

,Product_ID,Product_Name,Category,Sub_Category,Unit_Price,Cost_Price
0,PROD0001,Pro Storage 001,Home & Kitchen,Storage,58.57,35.68
1,PROD0002,Advanced Laptops 002,Electronics,Laptops,56.06,28.74
2,PROD0003,Everyday Mobiles 003,Electronics,Mobiles,117.90,89.08
3,PROD0004,Smart Accessories 004,Electronics,Accessories,88.05,44.87
4,PROD0005,Eco Appliances 005,Home & Kitchen,Appliances,50.00,32.02

    Order_ID  Order_Date Customer_ID Payment_Method Order_Status Shipping_Mode
0  ORD000001  2025-10-09   CUST03262            UPI    Delivered       Express
1  ORD000002  2026-05-15   CUST01118     Debit Card    Delivered      Standard
2  ORD000003  2026-01-11   CUST03240            UPI    Delivered      Standard
3  ORD000004  2024-02-12   CUST00911            UPI    Delivered      Standard
4  ORD000005  2025-12-19   CUST04310            UPI    Delivered       Express

  Order_Item_ID   Order_ID Product_ID  Quantity  Discount
0   ITEM0000001  ORD000682   PROD0168         3      0.05
1   ITEM0000002  ORD016616   PROD0078         3      0.05
2   ITEM0000003  ORD007980   PROD0164         4      0.15
3   ITEM0000004  ORD002089   PROD0112         3      0.10
4   ITEM0000005  ORD012216   PROD0082         4      0.00

In [6]:
print(customers.columns)
print(products.columns)
print(orders.columns)
print(order_items.columns)

Index(['Customer_ID', 'Customer_Name', 'Gender', 'Age', 'City', 'State',
       'Region', 'Customer_Segment', 'Registration_Date'],
      dtype='object')
Index(['Product_ID', 'Product_Name', 'Category', 'Sub_Category', 'Unit_Price',
       'Cost_Price'],
      dtype='object')
Index(['Order_ID', 'Order_Date', 'Customer_ID', 'Payment_Method',
       'Order_Status', 'Shipping_Mode'],
      dtype='object')
Index(['Order_Item_ID', 'Order_ID', 'Product_ID', 'Quantity', 'Discount'], dtype='object')

In [7]:
customers.info()
products.info()
orders.info()
order_items.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5010 entries, 0 to 5009
Data columns (total 9 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Customer_ID        5010 non-null   object
 1   Customer_Name      5010 non-null   object
 2   Gender             5010 non-null   object
 3   Age                5010 non-null   int64
 4   City               5007 non-null   object
 5   State              5010 non-null   object
 6   Region             5010 non-null   object
 7   Customer_Segment   5010 non-null   object
 8   Registration_Date  5010 non-null   object
dtypes: int64(1), object(8)
memory usage: 352.4+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Product_ID    200 non-null    object
 1   Product_Name  200 non-null    object
 2   Category      200 non-null    object
 3   Sub_Category  200 non-null    object
 4   Unit_Price    200 non-null    float64
 5   Cost_Price    200 non-null    float64
dtypes: float64(2), object(4)
memory usage: 9.5+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20000 entries, 0 to 19999
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Order_ID        20000 non-null  object
 1   Order_Date      20000 non-null  object
 2   Customer_ID     20000 non-null  object
 3   Payment_Method  19998 non-null  object
 4   Order_Status    20000 non-null  object
 5   Shipping_Mode   20000 non-null  object
dtypes: object(6)
memory usage: 937.6+ KB
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40000 entries, 0 to 39999
Data columns (total 5 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_Item_ID  40000 non-null  object
 1   Order_ID       40000 non-null  object
 2   Product_ID     40000 non-null  object
 3   Quantity       40000 non-null  int64
 4   Discount       39997 non-null  float64
dtypes: float64(1), int64(1), object(3)
memory usage: 1.5+ MB

In [8]:
orders["Order_Date"].dtype

dtype('O')

In [9]:
orders["Order_Date"] = pd.to_datetime(orders["Order_Date"])

In [10]:
orders["Order_Date"].dtype

dtype('<M8[ns]')

In [11]:
customers["Registration_Date"] = pd.to_datetime(customers["Registration_Date"])

In [12]:
customers.shape

(5010, 9)

In [13]:
customers.isnull().sum()

Customer_ID          0
Customer_Name        0
Gender               0
Age                  0
City                 3
State                0
Region               0
Customer_Segment     0
Registration_Date    0
dtype: int64

In [14]:
products.isnull().sum()

Product_ID      0
Product_Name    0
Category        0
Sub_Category    0
Unit_Price      0
Cost_Price      0
dtype: int64

In [15]:
orders.isnull().sum()

Order_ID          0
Order_Date        0
Customer_ID       0
Payment_Method    2
Order_Status      0
Shipping_Mode     0
dtype: int64

In [16]:
order_items.isnull().sum()

Order_Item_ID    0
Order_ID         0
Product_ID       0
Quantity         0
Discount         3
dtype: int64

In [17]:
print(customers.isnull().mean()*100)

Customer_ID          0.00000
Customer_Name        0.00000
Gender               0.00000
Age                  0.00000
City                 0.05988
State                0.00000
Region               0.00000
Customer_Segment     0.00000
Registration_Date    0.00000
dtype: float64

In [18]:
print(products.isnull().mean()*100)

Product_ID      0.0
Product_Name    0.0
Category        0.0
Sub_Category    0.0
Unit_Price      0.0
Cost_Price      0.0
dtype: float64

In [19]:
print(orders.isnull().mean()*100)

Order_ID          0.00
Order_Date        0.00
Customer_ID       0.00
Payment_Method    0.01
Order_Status      0.00
Shipping_Mode     0.00
dtype: float64

In [20]:
print(order_items.isnull().mean()*100)

Order_Item_ID    0.0000
Order_ID         0.0000
Product_ID       0.0000
Quantity         0.0000
Discount         0.0075
dtype: float64

In [21]:
customers.shape

(5010, 9)

In [22]:
customers[customers["City"].isnull()]

,Customer_ID,Customer_Name,Gender,Age,City,State,Region,Customer_Segment,Registration_Date
47,CUST00048,Rahul Reddy,Male,27,NaN,Bihar,East,Corporate,2022-02-20
913,CUST00914,Isha Verma,Male,35,NaN,Kerala,South,Small Business,2023-09-24
2022,CUST02023,Pooja Sharma,Male,24,NaN,Maharashtra,West,Consumer,2023-04-14

In [23]:
customers.shape

(5010, 9)

In [24]:
customers=customers.fillna({"City": "Unknown"})

In [26]:
orders[orders["Payment_Method"].isnull()]

,Order_ID,Order_Date,Customer_ID,Payment_Method,Order_Status,Shipping_Mode
321,ORD000322,2024-03-10,CUST01849,NaN,Delivered,Standard
7654,ORD007655,2024-01-06,CUST03661,NaN,Shipped,Standard

In [27]:
orders=orders["Payment_Method"].fillna("Unknown")

In [28]:
order_items[order_items["Discount"].isnull()]

      Order_Item_ID   Order_ID Product_ID  Quantity  Discount
121     ITEM0000122  ORD013894   PROD0137         2       NaN
875     ITEM0000876  ORD010193   PROD0085         2       NaN
14002   ITEM0014003  ORD017185   PROD0199         1       NaN

In [29]:
order_items["Discount"] = order_items["Discount"].fillna(0)

In [30]:
customers.duplicated().sum()

10

In [31]:
print(customers.duplicated())

0       False
1       False
2       False
3       False
4       False
        ...
5005     True
5006     True
5007     True
5008     True
5009     True
Length: 5010, dtype: bool

In [32]:
customers=customers.drop_duplicates()

In [33]:
customers.duplicated().sum()

0

In [34]:
customers.head()

,Customer_ID,Customer_Name,Gender,Age,City,State,Region,Customer_Segment,Registration_Date
0,CUST00001,Isha Mishra,Male,38,Ahmedabad,Gujarat,West,Consumer,2025-05-23
1,CUST00002,Amit Rao,Male,47,Lucknow,Uttar Pradesh,North,Consumer,2022-05-11
2,CUST00003,Rahul Rao,Female,28,Pune,Maharashtra,West,Consumer,2023-04-05
3,CUST00004,Divya Naidu,Male,28,Jaipur,Rajasthan,North,Corporate,2023-12-01
4,CUST00005,Varun Joshi,Male,19,Ranchi,Jharkhand,East,Small Business,2025-02-28

In [36]:
customers["Region"].value_counts()

Region
West       1293
North      1252
East       1227
South      1226
south         1
 SOUTH        1
Name: count, dtype: int64

In [37]:
customers["Region"]=(customers["Region"].str.strip().str.title())

In [38]:
customers["Region"].value_counts()

Region
West     1293
North    1252
South    1228
East     1227
Name: count, dtype: int64

In [39]:
products[["Unit_Price", "Cost_Price"]].describe()

       Unit_Price  Cost_Price
count  200.000000  200.000000
mean    94.083050   62.095050
std     73.443385   53.271427
min     50.000000   25.370000
25%     50.000000   33.205000
50%     64.515000   42.840000
75%    107.950000   68.040000
max    632.100000  504.740000

In [40]:
order_items[["Quantity", "Discount"]].describe()

           Quantity      Discount
count  40000.000000  40000.000000
mean       2.359600      0.097550
std        1.401316      0.077147
min        1.000000      0.000000
25%        1.000000      0.050000
50%        2.000000      0.100000
75%        3.000000      0.150000
max        6.000000      0.300000

In [42]:
order_items[order_items["Quantity"]<=0]

Empty DataFrame
Columns: [Order_Item_ID, Order_ID, Product_ID, Quantity, Discount]
Index: []

In [47]:
order_items[(order_items["Discount"]<0) | (order_items["Discount"]>1)]

Empty DataFrame
Columns: [Order_Item_ID, Order_ID, Product_ID, Quantity, Discount]
Index: []

In [ ]:
order_items = order_items.merge(products[["Product_ID", "Unit_Price", "Cost_Price"]], on="Product_ID", how="left"
)